# -*- coding: utf-8 -*-
"""Kuis SDA - Deret Fibonaci .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gpQYva5QmwrbHZ4sM5Y2XxlrfVdQegSH
"""

def fibo (n):
  if n < 1:
    return [n]

  listbeforeN = fibo (n - 1)
  angka1 = listbeforeN[-2] if len(listbeforeN) > 2 else 0
  angka2 = lisbeforeN[-1] if len(listbeforeN) > 2 else 1

  return listSebelumN + [angka1 + angka2]

panjang = int(input('Masukkan panjang deret:'))

def tampilkan (panjang):
  print(f'Deret Fibonacci untuk {panjang} bilangan adalah : ', fibo (panjang -1))


tampilkan (panjang)

n = eval(input('Masukkan panjang deret: '))

a, b = 0, 1
for i in range(n):
    print(a, end=' ')
    a, b = b, a+b

print()